#### Task-1

1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [6]:
#Exception handling
a =int(input("Enter the value a:"))
b =int(input("Enter the value b:"))

try:
    c =a/b
except Exception as e:
    print(e)
    b =int(input("Enter the valid num:"))
    c =a/b
else:
    print("Divisiable values")
finally:
    print("Finished I executed!")
    print(c)

Enter the value a:5
Enter the value b:2
Divisiable values
Finished I executed!
2.5


In [7]:
def divisiable(a,b):
    try:
        c=a/b
    except Exception as e:
        print(e)
        b =int(input("Enter the vaild num:"))
        c=a/b
    else:
        print("Divisiable values")
    finally:
        print("Finished I Executed!")
    return c

In [9]:
divisiable(8,0)

division by zero
Enter the vaild num:2
Finished I Executed!


4.0

2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

 - subjects=["Americans ","Indians"]
 - verbs=["play","watch"]
 - objects=["Baseball","Cricket"]

##### Hint: Subject,Verb and Object should be declared in the program as shown below

In [36]:
subjects = ['Americans','Indians']
verbs = ['play','watch']
objects = ['Baseball','Cricket']

In [37]:
sentence_list = [(sub+" "+veb+" "+obj)for sub in subjects for veb in verbs for obj in objects]

In [38]:
for sen in sentence_list:
    print(sen)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Task-2

1. Write a function so that the columns of the output matrix are powers of the input vector.

  - The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power 
of N - i - 1.  

 
#####   HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde. 

Define Interpolating polynomial as, <img src=".\Images\2.SVG" >

To find the coefficients of our polynomial, we solve the system  <img src=".\Images\1.SVG">

<img src=".\Images\3.SVG"> 

In order to solve the system, we will use an augmented matrix based on the Vandermonde matrix, and solve for the coefficients using Gaussian elimination. Substituting in our 'x' and 'y' values, our augmented matrix.

In [10]:
import numpy as np

In [12]:
x = np.array([1,2,3,5])

In [14]:
N=len(x)

In [15]:
N

4

In [16]:
np.vander(x,N)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [17]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [19]:
np.vander(x, increasing=1)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [33]:
#Linear algebra
np.linalg.det(np.vander(x))

48.00000000000007

In [34]:
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48

#screenshots :
https://drive.google.com/open?id=1ok3Rhp3bEOaODNrMQD3YzGfeRPUnUEK2